---

- name: Install apache httpd and required modules
  apt:
    name: apache2
    state: present
  tags:
    - apache

- name: automatically start apache
  service:
    name: apache2
    state: started
    enabled: yes
