---

- include: install.yml
  tags:
    - apache
    - apache-install

- include: config.yml
  tags:
    - apache
    - apache-config

- include: logging.yml
  tags:
    - apache
    - apache-logging
