---

- import_tasks: install.yml
  tags:
    - apache
    - apache-install

- import_tasks: config.yml
  tags:
    - apache
    - apache-config

- import_tasks: logging.yml
  tags:
    - apache
    - apache-logging
